# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {2}  -id {[BD 41-1271]}  -suppress 
set_msg_config  -ruleid {3}  -id {filemgmt 56-181}  -string {{ERROR: [filemgmt 56-181] Reference 'top_wrapper' contains sub-design file '/home/tansei/Desktop/cpu/2017/1stcore/cpu1/cpu1.srcs/sources_1/ip/fsub/fsub.xci'. This sub-design is not allowed in the reference due to following reason(s):
IP references are currently not enabled.}}  -suppress 
