# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tansei/Desktop/cpu/2017/1stcore/cpu_sim/cpu_sim.srcs/sources_1/ip/fsqrt_2/fsqrt.xci
# IP: The module: 'fsqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tansei/Desktop/cpu/2017/1stcore/cpu_sim/cpu_sim.srcs/sources_1/ip/fsqrt_2/fsqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fsqrt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/tansei/Desktop/cpu/2017/1stcore/cpu_sim/cpu_sim.srcs/sources_1/ip/fsqrt_2/fsqrt.xci
# IP: The module: 'fsqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tansei/Desktop/cpu/2017/1stcore/cpu_sim/cpu_sim.srcs/sources_1/ip/fsqrt_2/fsqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fsqrt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
