# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/tansei/Desktop/cpu/2017/example.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2}]

# IP: bd/design_2/ip/design_2_top_wrapper_0_1/design_2_top_wrapper_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_top_wrapper_0_1 || ORIG_REF_NAME==design_2_top_wrapper_0_1}]

# IP: bd/design_2/ip/design_2_blk_mem_gen_0_0/design_2_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_blk_mem_gen_0_0 || ORIG_REF_NAME==design_2_blk_mem_gen_0_0}]

# IP: bd/design_2/ip/design_2_blk_mem_gen_1_0/design_2_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_blk_mem_gen_1_0 || ORIG_REF_NAME==design_2_blk_mem_gen_1_0}]

# IP: bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_1 || ORIG_REF_NAME==design_2_clk_wiz_0_1}]

# XDC: bd/design_2/design_2_ooc.xdc
