# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tansei/cpu1/cpu1.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xci
# IP: The module: 'design_2_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tansei/cpu1/cpu1.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/tansei/cpu1/cpu1.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/tansei/cpu1/cpu1.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/tansei/cpu1/cpu1.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xci
# IP: The module: 'design_2_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tansei/cpu1/cpu1.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/tansei/cpu1/cpu1.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/tansei/cpu1/cpu1.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
