# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tansei/Desktop/cpu/2017/1stcore/cpu_sim/cpu_sim.srcs/sources_1/ip/fadd_4/fadd.xci
# IP: The module: 'fadd' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tansei/Desktop/cpu/2017/1stcore/cpu_sim/cpu_sim.srcs/sources_1/ip/fadd_4/fadd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fadd'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/tansei/Desktop/cpu/2017/1stcore/cpu_sim/cpu_sim.srcs/sources_1/ip/fadd_4/fadd.xci
# IP: The module: 'fadd' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tansei/Desktop/cpu/2017/1stcore/cpu_sim/cpu_sim.srcs/sources_1/ip/fadd_4/fadd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fadd'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
