# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/tansei/Desktop/cpu/2017/1stcore/example.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_top_wrapper_0_0/design_1_top_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_top_wrapper_0_0 || ORIG_REF_NAME==design_1_top_wrapper_0_0}]

# IP: bd/design_1/ip/design_1_fpu_wrapper_0_0/design_1_fpu_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fpu_wrapper_0_0 || ORIG_REF_NAME==design_1_fpu_wrapper_0_0}]

# IP: bd/design_1/ip/design_1_floating_point_0_1/design_1_floating_point_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_1 || ORIG_REF_NAME==design_1_floating_point_0_1}]

# IP: bd/design_1/ip/design_1_floating_point_1_0/design_1_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_1_0 || ORIG_REF_NAME==design_1_floating_point_1_0}]

# IP: bd/design_1/ip/design_1_floating_point_2_0/design_1_floating_point_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_2_0 || ORIG_REF_NAME==design_1_floating_point_2_0}]

# IP: bd/design_1/ip/design_1_floating_point_3_0/design_1_floating_point_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_3_0 || ORIG_REF_NAME==design_1_floating_point_3_0}]

# IP: bd/design_1/ip/design_1_floating_point_4_0/design_1_floating_point_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_4_0 || ORIG_REF_NAME==design_1_floating_point_4_0}]

# IP: bd/design_1/ip/design_1_floating_point_5_0/design_1_floating_point_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_5_0 || ORIG_REF_NAME==design_1_floating_point_5_0}]

# IP: bd/design_1/ip/design_1_floating_point_6_0/design_1_floating_point_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_6_0 || ORIG_REF_NAME==design_1_floating_point_6_0}]

# IP: bd/design_1/ip/design_1_floating_point_7_0/design_1_floating_point_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_7_0 || ORIG_REF_NAME==design_1_floating_point_7_0}]

# IP: bd/design_1/ip/design_1_floating_point_8_0/design_1_floating_point_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_8_0 || ORIG_REF_NAME==design_1_floating_point_8_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_0 || ORIG_REF_NAME==design_1_blk_mem_gen_1_0}]

# IP: bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_1 || ORIG_REF_NAME==design_1_axi_uartlite_0_1}]

# IP: bd/design_1/ip/design_1_uart_wrapper_0_0/design_1_uart_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart_wrapper_0_0 || ORIG_REF_NAME==design_1_uart_wrapper_0_0}]

# XDC: bd/design_1/design_1_ooc.xdc
